var num1 = 10;
var num2 = 20;
var result = null;
console.log(num1);
console.log(num2);
result = num1 > num2;
console.log(result);
result = num1 < num2;
console.log(result);
result = num1 >= num2;
console.log(result);
result = num1 <= num2;
console.log(result);
result = num1 == num2;
console.log(result);
result = num1 != num2;
console.log(result);
