var num1 = 20;
var num2 = 4;
var result;
result = num1 + num2;
console.log(result);
result = num1 - num2;
console.log(result);
result = num1 * num2;
console.log(result);
result = num1 / num2;
console.log(result);
result = num1 % num2;
console.log(result);
